//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipProgramiFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stok
    {
        public int stok_id { get; set; }
        public string urun_kod { get; set; }
        public string urun_ad { get; set; }
        public int urun_miktar { get; set; }
        public int kategori_id { get; set; }
        public int firma_id { get; set; }
        public int birim_id { get; set; }
        public int birim_miktar { get; set; }
        public Nullable<decimal> birim_fiyat { get; set; }
        public int depo_id { get; set; }
        public string resim { get; set; }
        public Nullable<System.DateTime> alis_tarih { get; set; }
    }
}
