//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipProgramiFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stok_Satis
    {
        public int stok_satis_id { get; set; }
        public int stok_id { get; set; }
        public int firma_id { get; set; }
        public int depo_id { get; set; }
        public int miktar { get; set; }
        public Nullable<decimal> net_fiyat { get; set; }
        public Nullable<int> kdv { get; set; }
        public Nullable<int> otv { get; set; }
        public Nullable<decimal> brut_fiyat { get; set; }
        public Nullable<System.DateTime> satis_tarih { get; set; }
    }
}
