//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipProgramiFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kullanici
    {
        public int kullanici_id { get; set; }
        public string tc_no { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string kullanici_ad { get; set; }
        public string kullanici_sifre { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public System.DateTime dogum_tarih { get; set; }
        public string cinsiyet { get; set; }
        public string resim { get; set; }
        public string hesap_durum { get; set; }
        public string tema { get; set; }
    }
}
