//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipProgramiFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Firma
    {
        public int firma_id { get; set; }
        public string firma_ad { get; set; }
        public string firma_adres { get; set; }
        public string firma_telefon { get; set; }
        public string vergi_dairesi { get; set; }
        public string hesap_no { get; set; }
        public string firma_aciklama { get; set; }
        public string firma_resmi { get; set; }
    }
}
