//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipProgramiFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Depo
    {
        public int depo_id { get; set; }
        public string depo_ad { get; set; }
        public string depo_yer { get; set; }
        public string depo_adres { get; set; }
        public string depo_sorumlusu { get; set; }
        public string depo_telefon { get; set; }
    }
}
